import { IndexedLevelData } from "@/types/types";

const levels: IndexedLevelData = {
  1: {
    gridSize: 3,
    maxMoves: 6,
    par: 5,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "T"
  }],
    validWords: ["RAM", "RAT"]
},
  10: {
  gridSize: 3,
    maxMoves: 10,
    par: 8,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["MOP", "TOP"]
},
  11: {
  gridSize: 3,
    maxMoves: 9,
    par: 7,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["RED", "BED"]
},
  12: {
  gridSize: 3,
    maxMoves: 4,
    par: 4,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["SUN", "SUM"]
},
  13: {
  gridSize: 3,
    maxMoves: 7,
    par: 6,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["NOT", "NET"]
},
  14: {
  gridSize: 3,
    maxMoves: 8,
    par: 7,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "J"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["JAW", "LAW"]
},
  15: {
  gridSize: 3,
    maxMoves: 8,
    par: 6,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["CUT", "GUT"]
},
  16: {
  gridSize: 3,
    maxMoves: 4,
    par: 4,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "V"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["VAN", "TAN"]
},
  17: {
  gridSize: 3,
    maxMoves: 4,
    par: 4,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["YES", "YET"]
},
  18: {
  gridSize: 3,
    maxMoves: 3,
    par: 3,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["FOG", "LOG"]
},
  19: {
  gridSize: 3,
    maxMoves: 6,
    par: 5,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "K"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["BIT", "KIT"]
},
  2: {
  gridSize: 3,
    maxMoves: 9,
    par: 7,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["BAG", "BAD"]
},
  20: {
  gridSize: 3,
    maxMoves: 9,
    par: 7,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["DIG", "FIG"]
},
  21: {
  gridSize: 3,
    maxMoves: 8,
    par: 7,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["MUD", "NOD"]
},
  22: {
  gridSize: 3,
    maxMoves: 6,
    par: 6,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "Z"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["ZIP", "RIP"]
},
  23: {
  gridSize: 3,
    maxMoves: 4,
    par: 4,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["WED", "WET"]
},
  24: {
  gridSize: 4,
    maxMoves: 16,
    par: 15,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["BOLT", "STAR", "OWL"]
},
  25: {
  gridSize: 4,
    maxMoves: 19,
    par: 18,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["FLY", "TRY", "SUN"]
},
  26: {
  gridSize: 4,
    maxMoves: 19,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["LAB", "BAT", "CAT"]
},
  27: {
  gridSize: 4,
    maxMoves: 9,
    par: 9,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["TAN", "NO", "TUG"]
},
  28: {
  gridSize: 4,
    maxMoves: 8,
    par: 8,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "T"
  }],
    validWords: ["MORE", "OWL", "EAT"]
},
  29: {
  gridSize: 4,
    maxMoves: 12,
    par: 11,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["TWO", "ONE", "SEA"]
},
  3: {
  gridSize: 3,
    maxMoves: 7,
    par: 7,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["HAT", "MAT"]
},
  30: {
  gridSize: 4,
    maxMoves: 7,
    par: 7,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["LACE", "CAT", "BAT"]
},
  31: {
  gridSize: 4,
    maxMoves: 17,
    par: 16,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "T"
  }],
    validWords: ["DEBT", "RED", "RIDE"]
},
  32: {
  gridSize: 4,
    maxMoves: 18,
    par: 16,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["FAN", "SUN", "LIFE"]
},
  33: {
  gridSize: 4,
    maxMoves: 14,
    par: 13,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "A"
  }],
    validWords: ["MAP", "WRAP", "FEW"]
},
  34: {
  gridSize: 4,
    maxMoves: 21,
    par: 18,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["ROW", "SEW", "LIST"]
},
  35: {
  gridSize: 4,
    maxMoves: 16,
    par: 14,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["HUG", "CURL", "ALE"]
},
  36: {
  gridSize: 4,
    maxMoves: 19,
    par: 17,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "E"
  }],
    validWords: ["FOG", "LOG", "SAFE"]
},
  4: {
  gridSize: 3,
    maxMoves: 5,
    par: 5,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "I"
  }],
    validWords: ["SIT", "PIT"]
},
  5: {
  gridSize: 3,
    maxMoves: 6,
    par: 6,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["SEA", "LAP"]
},
  6: {
  gridSize: 3,
    maxMoves: 5,
    par: 5,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["TIP", "HIT"]
},
  7: {
  gridSize: 3,
    maxMoves: 7,
    par: 6,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["SET", "PEN"]
},
  8: {
  gridSize: 3,
    maxMoves: 6,
    par: 6,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "O"
  }],
    validWords: ["BOW", "LOW"]
},
  9: {
  gridSize: 3,
    maxMoves: 5,
    par: 5,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["RIP", "DIP"]
},
  37: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["CARD", "ALSO", "ODE"]
},
  38: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "S"
  }],
    validWords: ["FISH", "FOUR", "AIR"]
},
  39: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "J"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["FLU", "JUMP", "POP"]
},
  40: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["ERA", "LACE", "AIR"]
},
  41: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["CITY", "COAT", "TRUE"]
},
  42: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "Z"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "Y"
  }],
    validWords: ["BLUR", "LAZY", "TYPO"]
},
  43: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["BAIT", "ARMY", "EYES"]
},
  44: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["BIG", "FOE", "GREY"]
},
  45: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["ASH", "CORN", "HARM"]
},
  46: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "D"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["GAS", "MY", "GOD", "SUM"]
},
  47: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "O"
  }],
    validWords: ["CUP", "PLOT", "ON", "SIT"]
},
  48: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["PENS", "ECHO"]
},
  49: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "M"
  }],
    validWords: ["PUSH", "HIM", "HELP"]
},
  50: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "Z"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "Q"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "I"
  }],
    validWords: ["QUIZ", "ZIPS", "HOP"]
},
  51: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "K"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["YOLK", "KNEW", "AS"]
},
  52: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "R"
  }],
    validWords: ["PRO", "AW", "HIP", "WHEN"]
},
  53: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "X"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "J"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "W"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "F"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["JINX", "BOWL", "FLEX"]
},
  54: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "R"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["YOGA", "HERO", "LEAP"]
},
  55: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "P"
  }],
    validWords: ["SUMO", "OILY", "PEAL"]
},
  56: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "K"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "A"
  }],
    validWords: ["TANK", "ACT", "SKY"]
},
  57: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "F"
  }],
    validWords: ["SOFT", "SYNC", "FLAG"]
},
  58: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["HAY", "ANT", "TIP", "UPS"]
},
  59: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "M"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["MATH", "LEGS", "GO"]
},
  60: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "L"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "P"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "N"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "H"
  }],
    validWords: ["LION", "HIPS", "IT"]
},
  61: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 3,
    isPartOfWord: false,
    letter: "G"
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: "U"
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 9,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 10,
    isPartOfWord: false,
    letter: "I"
  }, {
    id: 11,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 16,
    isPartOfWord: false,
    letter: "S"
  }],
    validWords: ["CUBE"]
},
  62: {
  gridSize: 4,
    maxMoves: 30,
    par: 19,
    tiles: [{
    id: 1,
    isPartOfWord: false,
    letter: "T"
  }, {
    id: 2,
    isPartOfWord: false,
    letter: "H"
  }, {
    id: 3,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 4,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 5,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 6,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 7,
    isPartOfWord: false,
    letter: "O"
  }, {
    id: 8,
    isPartOfWord: false,
    letter: "B"
  }, {
    id: 9,
    isPartOfWord: false,
    letter: "A"
  }, {
    id: 10,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 11,
    isPartOfWord: false,
    letter: "C"
  }, {
    id: 12,
    isPartOfWord: false,
    letter: "S"
  }, {
    id: 13,
    isPartOfWord: false,
    letter: "Y"
  }, {
    id: 14,
    isPartOfWord: false,
    letter: "E"
  }, {
    id: 15,
    isPartOfWord: false,
    letter: ""
  }, {
    id: 16,
    isPartOfWord: false,
    letter: ""
  }],
    validWords: ["TECH", "COY", "ABYS"]
  },
  63: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "N"
    }],
    validWords: ["PAN", "PET"]
  },
  64: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "Z"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "T"
    }],
    validWords: ["TOP", "ZOO"]
  },
  65: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["WIG", "BOW"]
  },
  66: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["DIP", "LIP"]
  },
  67: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["TOE", "EGG"]
  },
  68: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "G"
    }],
    validWords: ["EYE", "GEM"]
  },
  69: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "O"
    }],
    validWords: ["NEW", "ODE"]
  },
  70: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "P"
    }],
    validWords: ["DRY", "DIP"]
  },
  71: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "K"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "D"
    }],
    validWords: ["TIE", "KID"]
  },
  72: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["RUN", "ERA"]
  },
  73: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "N"
    }],
    validWords: ["END", "NET"]
  },
  74: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "E"
    }],
    validWords: ["LAW", "EGO"]
  },
  75: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "W"
    }],
    validWords: ["WIT", "TIN", "ON"]
  },
  76: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["BOY", "PUB"]
  },
  77: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "K"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["KID", "NIL"]
  },
  78: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "K"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["DOT", "OAK"]
  },
  79: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "I"
    }],
    validWords: ["BAR", "BIT"]
  },
  80: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "J"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "I"
    }],
    validWords: ["JET", "ICE"]
  },
  81: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "F"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "L"
    }],
    validWords: ["FLY", "EYE", "IF"]
  },
  82: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["CUT", "UP"]
  },
  83: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "E"
    }],
    validWords: ["BUN", "NOW", "BE"]
  },
  84: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["INN", "NOT"]
  },
  85: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "E"
    }],
    validWords: ["MET", "TWO"]
  },
  86: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "O"
    }],
    validWords: ["DUD", "POD"]
  },
  87: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "P"
    }],
    validWords: ["NUT", "TAP"]
  },
  88: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "R"
    }],
    validWords: ["AIR", "PRO"]
  },
  89: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "W"
    }],
    validWords: ["DAY", "GEM", "AWE"]
  },
  90: {
    gridSize: 3,
    maxMoves: 30,
    par: 19,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["DEW", "LOW"]
  }
}

export default levels