import { IndexedLevelData } from "@/types/types";

const newLevels: IndexedLevelData = {
  201: {
    gridSize: 5,
    maxMoves: 31,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "J"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "K"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 19,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 22,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "B"
    }],
    validWords: ["JUMBO", "KEPT", "TRUCK"]
  },
  202: {
    gridSize: 5,
    maxMoves: 22,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 22,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["ASH", "PULSE", "SAUCE"]
  },
  203: {
    gridSize: 5,
    maxMoves: 35,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 18,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "P"
    }],
    validWords: ["HEAD", "SPICE", "SHOW"]
  },
  204: {
    gridSize: 5,
    maxMoves: 26,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["CLAW", "LEG", "PIGS", "PUT"]
  },
  205: {
    gridSize: 5,
    maxMoves: 27,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: "F"
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "N"
    }],
    validWords: ["FANCY", "TURF", "GRAIN"]
  },
  206: {
    gridSize: 5,
    maxMoves: 21,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["EPIC", "SCALP", "MOP"]
  },
  207: {
    gridSize: 5,
    maxMoves: 31,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 23,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 24,
      isPartOfWord: false,
      letter: "F"
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["ACHE", "IDEAL", "FILMS"]
  },
  208: {
    gridSize: 5,
    maxMoves: 25,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "C"
    }],
    validWords: ["TAMED", "BENCH"]
  },
  209: {
    gridSize: 5,
    maxMoves: 38,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 18,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["BACON", "READY", "WORLD"]
  },
  21: {
    gridSize: 4,
    maxMoves: 16,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["NERD", "AGED"]
  },
  210: {
    gridSize: 5,
    maxMoves: 28,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 23,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 24,
      isPartOfWord: false,
      letter: "F"
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "G"
    }],
    validWords: ["BOAR", "RIGHT", "LEFT"]
  },
  211: {
    gridSize: 5,
    maxMoves: 27,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 19,
      isPartOfWord: false,
      letter: "V"
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["TYPE", "OLIVE", "PANIC"]
  },
  212: {
    gridSize: 5,
    maxMoves: 30,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 19,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 24,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "Y"
    }],
    validWords: ["DENSE", "MAYOR", "WITCH"]
  },
  213: {
    gridSize: 5,
    maxMoves: 26,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "P"
    }],
    validWords: ["LAUGH", "POINT"]
  },
  214: {
    gridSize: 5,
    maxMoves: 35,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "P"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: "J"
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["JUMBO", "IMPLY", "OBEYS"]
  },
  215: {
    gridSize: 5,
    maxMoves: 27,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: "R"
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["HOURS", "AS", "MIND"]
  },
  216: {
    gridSize: 5,
    maxMoves: 31,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "T"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: "B"
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 22,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["SOB", "BEGIN", "TANS"]
  },
  217: {
    gridSize: 5,
    maxMoves: 28,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: "C"
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "S"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "Z"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 12,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 13,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: "D"
    }],
    validWords: ["GAS", "GEL", "IDLE", "ZINC"]
  },
  218: {
    gridSize: 5,
    maxMoves: 21,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 2,
      isPartOfWord: false,
      letter: "A"
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 5,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 6,
      isPartOfWord: false,
      letter: "W"
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: "Y"
    }, {
      id: 9,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 15,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 16,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: "H"
    }, {
      id: 21,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "L"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["AN", "DO", "WHY", "YELL"]
  },
  219: {
    gridSize: 5,
    maxMoves: 26,
    par: 30,
    tiles: [{
      id: 1,
      isPartOfWord: false,
      letter: "U"
    }, {
      id: 2,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 3,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 4,
      isPartOfWord: false,
      letter: "G"
    }, {
      id: 5,
      isPartOfWord: false,
      letter: "N"
    }, {
      id: 6,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 7,
      isPartOfWord: false,
      letter: "D"
    }, {
      id: 8,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 9,
      isPartOfWord: false,
      letter: "O"
    }, {
      id: 10,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 11,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 12,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 13,
      isPartOfWord: false,
      letter: "J"
    }, {
      id: 14,
      isPartOfWord: false,
      letter: "E"
    }, {
      id: 15,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 16,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 17,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 18,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 19,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 20,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 21,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 22,
      isPartOfWord: false,
      letter: ""
    }, {
      id: 23,
      isPartOfWord: false,
      letter: "I"
    }, {
      id: 24,
      isPartOfWord: false,
      letter: "M"
    }, {
      id: 25,
      isPartOfWord: false,
      letter: ""
    }],
    validWords: ["MIND", "DOE", "JUG"]
  }
}