export const levelCompleteText = [
  "Word up! You <span class='text-purple-400 font-medium uppercase'>did it</span>!",
  "Well done! You’ve <span class='text-purple-400 font-medium uppercase'>cracked</span> the code!",
  "You’ve got the words on <span class='text-purple-400 font-medium uppercase'>lock</span>!",
  "You <span class='text-purple-400 font-medium uppercase'>nailed</span> it! Can’t stop you!",
  "You’re on <span class='text-purple-400 font-medium uppercase'>fire</span>! Nothing can stop you!",
  "You found the <span class='text-purple-400 font-medium uppercase'>key</span> to the puzzle!",
  "You have a way with <span class='text-purple-400 font-medium uppercase'>words</span>!",
  "You’re a letter locking <span class='text-purple-400 font-medium uppercase'>legend</span>!",
  "You’ve <span class='text-purple-400 font-medium uppercase'>outdone</span> yourself!",
  "You’re a puzzle <span class='text-purple-400 font-medium uppercase'>perfectionist</span>!",
  "You’ve reached the pinnacle of <span class='text-purple-400 font-medium uppercase'>wordplay</span>!",
  "You’ve <span class='text-purple-400 font-medium uppercase'>unlocked</span> your potential!",
  "Great job! Onto your next <span class='text-purple-400 font-medium uppercase'>challenge</span>!",
  "You’ve <span class='text-purple-400 font-medium uppercase'>locked</span> in your victory! Well done!",
  "You unscrambled those letters like a <span class='text-purple-400 font-medium uppercase'>pro</span>!",
  "Congratulations, you’ve <span class='text-purple-400 font-medium uppercase'>unscrambled</span> your way to the next level!",
  "Awesome! Nothing can stop <span class='text-purple-400 font-medium uppercase'>you</span>!",
  "You. Are. <span class='text-purple-400 font-medium uppercase'>Unstoppable</span>.",
  "High five! You <span class='text-purple-400 font-medium uppercase'>did</span> it!",
  "You’ve truly <span class='text-purple-400 font-medium uppercase'>letter-matched</span> your way to success!",
  "Alphabetically <span class='text-purple-400 font-medium uppercase'>superior</span>! You cracked it!",
  "You've got a way with <span class='text-purple-400 font-medium uppercase'>words... and locks</span>!",
  "<span class='text-purple-400 font-medium uppercase'>Puzzles</span> are scared of you at this point!",
  "Another level, another set of <span class='text-purple-400 font-medium uppercase'>unlocked words</span>!",
  "<span class='text-purple-400 font-medium uppercase'>Unscrambled</span> to perfection, well done!",
  "You're a word puzzle's <span class='text-purple-400 font-medium uppercase'>worst nightmare</span>!",
  "Whoa, did you just <span class='text-purple-400 font-medium uppercase'>pick</span> that lock with your mind?",
  "You're <span class='text-purple-400 font-medium uppercase'>schooling</span> these puzzles, they'll need a tutor!"
]

export const levelFailedText = [
  "Locked out! Ready for a rematch?",
  "This round was a toughie. Try again!",
  "So close! The puzzle remains unlocked.",
  "Almost there! This lock's a bit tricky.",
  "This puzzle put up a good fight.",
  "The words were just out of reach. Try again!",
  "Give this lock another crack. You've got this!",
  "Got stumped? Don't worry, you got this!",
  "Tough lock to crack. Try again!",
  "This round wasn't in your favor. Comeback time?",
  "The lock pulled a quick one. Rematch?",
  "The lock threw a curveball. Ready to try again?",
  "The words won this round. Time for a rematch?",
  "Missed it by a whisker! You'll get it next time.",
  "This round slipped away. Grab it next time!",
  "This puzzle played hard to get. Catch it next time!",
  "This lock remains a mystery. Unravel it next time!",
  "This round didn't spell success. Next one will!",
]

export const levelFailedWatchAdText = [
  "You're right on the brink! A few more moves and you'll have it!",
  "So close! An extra move could make all the difference!",
  "The next level is within your grasp! Don't give up now!",
  "Keep going, you're almost there! Just a little push could do it!",
  "You're one step away from victory! Don't let it slip away!",
  "You're on the edge of greatness! Seize the chance!",
  "Almost there! An extra move could be the game-changer!",
  "You're knocking on the door of success! Just a bit more to go!",
  "You're so close you can almost taste it! Go on, give it another shot!",
  "You're on the verge of cracking it! Don't stop now!"
]